import { ReactNode } from 'react';

import { Roboto } from 'next/font/google';

import Footer from '@/components/shared/client/footer/footer';
import Navbar from '@/components/shared/client/navbar/navbar';

import './globals.css';
import { twMerge } from 'tailwind-merge';

const titillium_Web = Roboto({ display: 'auto', subsets: ['latin'], weight: '500' });

export const metadata = {
  description: 'Generated by create next app',
  title: 'Create Next App',
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <body className={twMerge('bg-primary-main', titillium_Web.className)}>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
